default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: 5432
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: doit_development

test:
  <<: *default
  database: doit_test

production:
  <<: *default
  database: <%= ENV['RDS_DBNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOST'] %>
