version: "3"

volumes:
  db-data:
  bundle_data:

services:
  backend:
    container_name: backend
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/doit:cached
      - bundle_data:/usr/local/bundle:cached
      - /doit/tmp
      - /doit/log
      - /doit/.git
    environment:
      - DATABASE_PASSWORD=postgres
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  frontend:
    container_name: frontend
    build: ./frontend
    command: yarn run start
    volumes:
      - ./frontend:/doit
      - /doit/node_modules
    ports:
      - "8080:8080"

  db:
    container_name: db
    image: postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  smtp:
    container_name: smtp
    image: schickling/mailcatcher
    ports:
      - "1080:1080"