version: '3'

volumes:
  db-data:
  bundle_data:

services:
  api:
    build: ./api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - ./api:/doit:cached
      - bundle_data:/usr/local/bundle:cached
      - /doit/tmp
      - /doit/log
      - /doit/.git
    depends_on:
      - db

  web:
    container_name: web
    build:
      context: ./front
      dockerfile: Dockerfile
    command: yarn run start
    volumes:
      - ./front:/doit
      - /doit/node_modules
    ports:
      - '8080:8080'

  db:
    container_name: db
    image: postgres
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
      - '5432:5432'

  smtp:
    container_name: smtp
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
