version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/doit
      - bundle:/doit/vendor/bundle
      - node_modules:/doit/node_modules
      - /doit/vendor
      - /doit/tmp
      - /doit/log
      - /doit/.git
    ports:
      - 3000:3000
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    depends_on:
      - db
      - webpacker
  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080" #http://localhost:1080/でmailcatcherが開けます
      - "1025:1025"
  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/doit
    ports:
      - '3035:3035'
    tty: false
    stdin_open: false
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
volumes:
  bundle:
  node_modules: