version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/doit:delegated
      - bundle:/doit/vendor/bundle
      - node_modules:/doit/node_modules
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:3035
    depends_on:
      - db
  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080" #http://localhost:1080/でmailcatcherが開けます
volumes:
  bundle:
  node_modules: