version: 2
jobs:
  build:
    machine: true
    steps:

      #ローカルでCLIを使ってCircleCIをテストする時のエラー回避用
      - run:
          name: Local build handling
          command: |
            if [[ ${CIRCLE_SHELL_ENV} =~ "localbuild" ]]; then
              if [ -d /workdir ]; then
                ln -s /workdir /tmp/_circleci_local_build_repo
              else
                echo "Run this local build using: circleci build -v \$(pwd):/workdir"
                exit 1
              fi
            fi

      - checkout

      - run:
          name: Dockerコンテナの作成
          command: |
            docker-compose build

      - run:
          name: Dockerコンテナの立ち上げ
          command: |
            docker-compose up -d

      - run:
          name: データベースの作成
          command: |
            docker-compose exec backend bundle exec rails db:create
            docker-compose exec backend bundle exec rails db:migrate

      - run:
          name: RSpecの実行
          command: docker-compose exec backend bundle exec rspec

      - run:
          name: Jestの実行
          command: docker-compose exec frontend yarn run test

      - run:
          name: Dockerコンテナの終了
          command: docker-compose down