version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    working_directory: ~/doit
    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: docker-compose up
          command: docker-compose up --build -d

      - run:
          name: Create database
          command: |
            docker-compose exec web bundle exec rails db:create
            docker-compose exec web bundle exec rails db:migrate

      - run:
          name: Rspec
          command: docker-compose exec web bundle exec rspec

      - run:
          name: Jest
          command: |
            docker-compose exec web yarn install
            docker-compose exec web yarn run test

      - run:
          name: docker-compose down
          command: docker-compose down