default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: app_user_role
  password: password
  pool: 5

development:
  <<: *default
  database: doit_development

test:
  <<: *default
  database: doit_test
  host: <%= ENV['PGHOST'] || 'db' %>

production:
  <<: *default
  database: <%= ENV['RDS_DBNAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
